name: tj-Changed files
run-name: ${{ github.actor }} is learning GitHub Actions
on:
    push:
        paths:
            - "reportes/**"


jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
            files : |
                reportes/**

      - name: List all changed files
        run: |
            for file in ${{steps.changed-files.outputs.all_changed_files}}; do
                echo "$file ha cambiado"
            done

    