name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Diferencias
        run: |
            if [[ $(git diff --name-only HEAD~1) == "reporte1.txt" ]]; then
            echo "El archivo file1 fue modificado."
            elif [[ $(git diff --name-only HEAD~1) == "reporte2.txt" ]]; then
            echo "El archivo file2 fue modificado."
            fi

      - name: Evaluando con for
        run: |
            echo git diff --name-only HEAD~1 | jq -r '.[]
            files=$(git diff --name-only HEAD~1 | jq -r '.[]')
            for file in $files; do
                echo "El archivo $file fue modificado."
            done