name: Using Dorny paths Filter
on: 
    push:
        paths:
          - "reportes/**"

jobs:
  deployReport1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            reporte1:
              - 'reportes/reporte1.txt'
            reporte2:
              - 'reportes/reporte2.txt'
            reporte3:
              - 'reportes/reporte3.txt'
            reporte4:
              - 'reportes/reporte4.txt'
      
        # run only if some file in 'src' folder was changed
      - if: steps.filter.outputs.reporte1 == 'true'
        run: |
            echo "Reporte 1 modificado"
      - if: steps.filter.outputs.reporte2 == 'true'
        run: |
            echo "Reporte 2 modificado"
      - if: steps.filter.outputs.reporte3 == 'true'
        run: |
            echo "Reporte 3 modificado"

      - if: steps.filter.outputs.reporte4 == 'true'
        run: |
            echo "Reporte 4 modificado"