name: learn-github-actions
on: 
    push:
        paths:
          - "reportes/**"

jobs:
  deployReport1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            reporte1:
              - 'reportes/reporte1.txt'
      
        # run only if some file in 'src' folder was changed
      - if: steps.filter.outputs.reporte1 == 'true'
        run: |
            echo "Reporte 1 modificado"


